name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (no-default-features)
      run: cargo test --verbose --no-default-features
    - name: Run tests (no-default-features, lookup)
      run: cargo test --verbose --no-default-features --features lookup
    - name: Run tests (no-default-features, fractions_simplify)
      run: cargo test --verbose --no-default-features --features fractions_simplify
